/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.DataStorageException;
import data.Patient;
import data.Practioner;
import javax.swing.JOptionPane;

/**
 *
 * @author madala
 */
public final class Homepage extends javax.swing.JFrame {
    private Practioner objPractioner = null;

    private Homepage() {
        initComponents();
    }
    
    public void setScreenTitle(){
        this.setTitle("Welcome " +objPractioner.getPosition()+" "+
                objPractioner.getLastName()+" "+objPractioner.getFirstName()+" "+
               "Username : "+objPractioner.getUsername());
        
    }

    /**
     * Creates new form Homepage
     * @param objPrac
     */
    public Homepage(Practioner objPrac) {
        initComponents();
        
        objPractioner = objPrac;
        setScreenTitle();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        miEnterDetails = new javax.swing.JMenuItem();
        miViewRecords = new javax.swing.JMenuItem();
        miStats = new javax.swing.JMenuItem();
        miSearch = new javax.swing.JMenuItem();
        mnClose = new javax.swing.JMenu();
        miClose = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu1.setText("jMenu1");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N

        jMenu2.setText("File");

        miEnterDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miEnterDetails.setText("Enter Patient Details");
        miEnterDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEnterDetailsActionPerformed(evt);
            }
        });
        jMenu2.add(miEnterDetails);

        miViewRecords.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        miViewRecords.setText("View Patient Records");
        miViewRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miViewRecordsActionPerformed(evt);
            }
        });
        jMenu2.add(miViewRecords);

        miStats.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        miStats.setText("Patient Stats");
        miStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStatsActionPerformed(evt);
            }
        });
        jMenu2.add(miStats);

        miSearch.setText("Search For  Patient");
        miSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSearchActionPerformed(evt);
            }
        });
        jMenu2.add(miSearch);

        jMenuBar1.add(jMenu2);

        mnClose.setText("Close Application");
        mnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCloseActionPerformed(evt);
            }
        });

        miClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miClose.setText("Close");
        miClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCloseActionPerformed(evt);
            }
        });
        mnClose.add(miClose);

        jMenuBar1.add(mnClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miEnterDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEnterDetailsActionPerformed
        PatientRegistrationScreen frmPatient = 
                new PatientRegistrationScreen(objPractioner);
        frmPatient.setVisible(true);
        dispose();
    }//GEN-LAST:event_miEnterDetailsActionPerformed

    private void mnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCloseActionPerformed
       
                
    }//GEN-LAST:event_mnCloseActionPerformed

    private void miCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCloseActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "Do you want to exit?", 
               "Close", JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if(res == JOptionPane.YES_OPTION){
            try {
                Patient.terminate();
                System.exit(0);
            } catch (DataStorageException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_miCloseActionPerformed

    private void miViewRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miViewRecordsActionPerformed
        ViewPatientsRecords frmViewRecords = 
                new ViewPatientsRecords(objPractioner);
        frmViewRecords.setVisible(true);
        dispose();
    }//GEN-LAST:event_miViewRecordsActionPerformed

    private void miStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStatsActionPerformed
        StatisticsScreen frmStats = new StatisticsScreen(objPractioner);
        frmStats.setVisible(true);
    }//GEN-LAST:event_miStatsActionPerformed

    private void miSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSearchActionPerformed
        PatientSearchScreen frmSearch = new PatientSearchScreen(objPractioner);
        frmSearch.setVisible(true);
    }//GEN-LAST:event_miSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Homepage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem miClose;
    private javax.swing.JMenuItem miEnterDetails;
    private javax.swing.JMenuItem miSearch;
    private javax.swing.JMenuItem miStats;
    private javax.swing.JMenuItem miViewRecords;
    private javax.swing.JMenu mnClose;
    // End of variables declaration//GEN-END:variables
}
